### ISSUE TITLE
Get-MrkOrgEndpoint

### ISSUE THREAD

**Issue by CalebBartle** [sanderkl/PSMeraki#19]
Sanderkl,

You don't need to completely break your existing configuration of this function, you just need to update it to the correct context so it can properly load organization data.

Here is an example of how it is done (I use $OrgID internally through another assignment process)

function Get-MrkOrgEndpoint {
            #This has been edited to address several redirection errors
            [CmdletBinding()]
            Param ()
            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
            if (!$orgBaseUri){
                $orgURI = Invoke-RestMethod -Method Get 'https://api.meraki.com/api/v1/organizations' -Headers (Get-MrkRestApiHeader)
                $orgURI = ($orgURI.Where({ $_.id -eq $OrgID })).url
                $global:orgBaseUri = ($orgURI.Substring(0, $orgURI.IndexOf('/o')) + "/api/v1")
            }
            Return $orgBaseUri
    }

**Comment by sanderkl** [comment]
"Get-MrkOrgEndpoint" is was the result of a workaround, because api.meraki.com caused some problems while redirecting requests. This was 2 years ago, I wasn't able to find out what the exact problem was. That's why I created that cmdlet, because when the module communicated the the organizational unique API endpoint, there was no redirecting and everything worked fine. 

When I re-tested the module in June this year , before releasing v2. I found out that redirecting for api.meraki.com did work. so the workaround was no longer needed and removed the cmdlet.
